# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Curcifer Tech
email: info@curcifer.tech
description: >- # this means to ignore newlines until "baseurl:"
  Hi Curcifer Techies, welcome to Landing sites of Curcifer Tech
  Please feel free to dive into the blogs and project.
github_username:  curcifer
copyright:    >
  © Copyright 2022 [Curcifer Techies](https://curcifer.tech)
repository:   curcifer/ct.github.io

author:
  name: Curcifer Techies

sass:
  sass_dir: _sass

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: nsnull0/monophase@main

paginate: 2
paginate_path: "/blog/page:num/"